language: julia
julia:
  - nightly
  - 1.7
  - 1.0

jobs:
  include:
    - stage: "Documentation"
      julia: 1.7
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
